//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPGP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class UtilisateursInformations
    {
        public string Id { get; set; }

        [Required]
        public string Prenom { get; set; }

        public string Nom { get; set; }

        public string Ville { get; set; }

        [Required]
        public string Mail { get; set; }
        public string Descriptif { get; set; }

        [Required]
        public int Age { get; set; }

        [Required]
        public string Sexe { get; set; }

        [Required]
        public string InteressePar { get; set; }
    }
}
